### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Narsil**

### CODE REVIEW

**Comment by Narsil** [comment]
@stas00

**Comment by stas00** [comment]
That's how it was written originally and then @thomasw21 asked to remove the link. So are you in sync and you want it public again?

**Review by thomasw21 — APPROVED** [review]
Yep! @Narsil took care of cleaning up the repo.

**Comment by stas00** [comment]
Thank you, @Narsil and @thomasw21!

**Comment by mayank31398** [comment]
Thanks guys

**Pull request merged**
