### PR TITLE
Fix asynchronous issues for server deployments

### PR DESCRIPTION
**Pull request by mayank31398**
If multiple people query BLOOM deployed with MII then, I run into event loop is already running issue.
I tried to fix this by awaiting the generate method but that just leads to MII getting stuck

No idea how to fix this

### CODE REVIEW

**Comment by mayank31398** [comment]
https://github.com/microsoft/DeepSpeed-MII/issues/54
https://github.com/huggingface/transformers-bloom-inference/issues/6

**Comment by mayank31398** [comment]
The problem is there is already an event loop running inside MII which (I think) doesn't like being awaited outside.

**Comment by mayank31398** [comment]
I have fixed it @stas00 
I am starting a Flask server using gunicorn with 1 worker.
Had to change to Flask since FastAPI is meant to be asynchronous and is not compatible with gunicorn.

**Comment by mayank31398** [comment]
I went through the codebase of DeepSpeed-MII and I believe there is no easy solution to this.
The problem is DS-MII is using asyncio for launching jobs on 8 GPU workers and hence FastAPI is interfering with it.
The current solution (though a synchronous one which was supposed to be the case earlier too) fixes the problem.

**Comment by mayank31398** [comment]
I will leave merging to you :)

**Comment by mayank31398** [comment]
closes: 
closes: https://github.com/huggingface/transformers-bloom-inference/issues/6

**Comment by stas00** [comment]
That's interesting, asyncio is quite awesome - we use it for firing off distributed tests from `pytest` which goes haywire w/o it.

Good to hear you found a workaround, Mayank! I'm not sure if perhaps it'd be useful to communicate to MII folks to have an option to use something else besides asyncio when used with fastapi and similar components? Surely, at least they would like to know and perhaps document that some webserver front-ends might be incompatible with it?

You don't need my approval to merge - the server section is completely for you to rule ;) And I don't have a set up to test it anyway.

**Comment by mayank31398** [comment]
@jeffra @RezaYazdaniAminabadi fyi
DS-MII is incompatible with the asynchronous executions of FastAPI.
Please read the conversations in this thread ^^

**Pull request merged**
