### PR TITLE
Add support for serving deepspeed models using flask

### PR DESCRIPTION
**Pull request by arvindsun**
I will add add documentation and examples if there is interest in merging.

### CODE REVIEW

**Comment by arvindsun** [comment]
Got this working on a 8x40GB - A100 GPU machine. 

``` python -m inference_server.flask_serve   --model_name microsoft/bloom-deepspeed-inference-int8 --model_class AutoModelForCausalLM  --dtype int8 --deployment_framework ds_inference```

**Comment by mayank31398** [comment]
Hey @arvindsun , the repository already has this functionality 😅

**Comment by mayank31398** [comment]
You can look at the makefile in the repo for serving.
Btw please note everything will be sequential and users will wait in queue for their turn :(
you can use inference_server/examples to see how to fire a query

**Comment by mayank31398** [comment]
Let me know if we can close this or if I misunderstood the PR.

**Comment by arvindsun** [comment]
Got it - thanks for the quick response! And thank you for your work on this repo!

**Pull request closed without merging**
