### PR TITLE
fix: deadlock in `bloom-ds-inference.py`

### PR DESCRIPTION
**Pull request by anselmwang**
In `bloom-ds-inference.py`, rank 0 calls `dist.barrier()` while other processes don't. Cause deadlock forever.

### CODE REVIEW

**Comment by mayank31398** [comment]
Hi @anselmwang, I am afraid the earlier code was correct right?
All ranks call barrier(), its just that 0 takes longer to reach it since it is stuck downloading the model

**Comment by mayank31398** [comment]
the second dist.barrier is also called by all processes. barrier is outside if condition.
https://github.com/huggingface/transformers-bloom-inference/blob/4a316baa075e141bedf27af715b6c5a0871c52bd/bloom-inference-scripts/bloom-ds-inference.py#L184-L186

**Comment by mayank31398** [comment]
nvm got it. This bug was not there earlier and might have crept in when we refactored this script.
Thanks a lot.

**Comment by mayank31398** [comment]
Thanks @anselmwang I have merged your changes and made some changes on top of it.
I feel like this is better:
https://github.com/huggingface/transformers-bloom-inference/commit/a9bc5fd052df9ff5832fdc4868f9c50a9cdf13f1
Thanks a lot for catching this :)

**Comment by anselmwang** [comment]
Love your changes. Thanks!

**Pull request merged**
