### PR TITLE
Support for deepspeed int8 model

### PR DESCRIPTION
**Pull request by arvindsun**
* Add support for deepspeed int8 models so that we can run inference on a 8x40 A100 GPU machine
* Add convenient GET wrapper and autoboxing so that a simple `/generate/?text=<prefix query>` works.

### CODE REVIEW

**Comment by mayank31398** [comment]
@arvindsun thanks for this. I had written code in mind keeping int8 support. But glad to see that it works without any significant changes. I will test in on my side and merge

Also, why have you introduced a GET method?
Is it necessary?

**Comment by arvindsun** [comment]
The GET method with a simple query parameter makes it convenient to test using a browser - you can do `http://<host>:5000/generate/?text=<>`

**Comment by mayank31398** [comment]
Oh I see, I didn't know that :)

**Comment by mayank31398** [comment]
I would say, this is not really needed @arvindsun
I think a simple curl command would be fine.
I think a simple change to the makefile would be fine.
Also, you can add a curl command for the POST method if needed.

**Comment by arvindsun** [comment]
Updated to only preserve Makefile change. Still think the GET is useful - will see if I can convince you in a different PR with better examples :)

**Pull request merged**
